debug: false
info:
  id: ${spring.application.name}
server:
  port: ${PORT:${SERVER_PORT:0}}

#logging:
#  level:
#    org.springframework.security: ERROR
#    com.netflix.eureka: ERROR
#    com.netflix.discovery: ERROR

eureka:
  hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url-poll-interval-seconds: 60
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    prefer-ip-address: true
