server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url-poll-interval-seconds: 60