spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weifwStudy/spring-cloud-demo.git
          search-paths: \*
#eureka:
#  hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8762/eureka/
#    healthcheck:
#      enabled: true
#    register-with-eureka: true
#    fetch-registry: false
#    eureka-service-url-poll-interval-seconds: 60
#  instance:
#    statusPageUrlPath: ${management.context-path}/info
#    healthCheckUrlPath: ${management.context-path}/health
#    prefer-ip-address: true
info:
  id: ${spring.application.name}
server:
  port: 8888